import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import AppBarComp from "@/components/AppBar";
import { StyledRoot } from "@/theme/StyledRoot";
import "./global.css";
import { Colors } from "@/theme/colors";
import { Box } from "@mui/material";
import { CookieProvider } from "@/context/cookie.context";
import { CustomerProvider } from "@/context/customer.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <link
        rel="stylesheet"
        type="text/css"
        charSet="UTF-8"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
      />
      <body
        className={inter.className}
        style={{ backgroundColor: Colors.black, color: Colors.white }}
      >
        <AppRouterCacheProvider>
          <StyledRoot>
            <CustomerProvider>
              <CookieProvider>
                <AppBarComp />
                <Box sx={{ paddingTop: "75px" }}>{children}</Box>
              </CookieProvider>
            </CustomerProvider>
          </StyledRoot>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
